# My First Notebook — Python for Geoscientists, Video 1

This notebook follows along with **Video 1** of the *Python for Geoscientists* series
on [Bots on the Ground](https://botsontheground.com).

By the end of this notebook you will have:

1. Run your first piece of Python code
2. Worked with variables
3. Loaded a real drillhole dataset
4. Computed some simple statistics from it

Watch the video here: [Python for Geoscientists, Part 1](https://youtu.be/02YymGb9y_Y)

If you're new to notebooks: a notebook is made of *cells*. Some cells are text (like this one),
and some are code. To run a code cell, click on it and press **Shift + Enter**.

## 1. Hello, geologist

The first thing every Python tutorial does is print "Hello, world." We'll do the
same, with a small geological twist. Run the cell below.

In [1]:
print("Hello from a geologist")

Hello from a geologist

## 2. Variables

A *variable* is a name you give to a value, so you can use it later.

Text values go in quotes. Numbers do not. That's most of what you need to know
for now.

In [2]:
hole_id = "DDH-001"
grade_gpt = 4.7

print(hole_id)
print(grade_gpt)

DDH-001
4.7

You can use variables in calculations:

In [3]:
interval_length_m = 4.5
contained_metal_g_per_t = grade_gpt * interval_length_m

print(f"A {interval_length_m} m interval at {grade_gpt} g/t is worth {contained_metal_g_per_t} gram-metres")

A 4.5 m interval at 4.7 g/t is worth 21.150000000000002 gram-metres

## 3. Loading a real dataset

This is where Python becomes genuinely useful. We'll load a small drillhole assay
file with `pandas`, a library built for working with tabular data.

**Before running the next cell**, make sure `assays.csv` is uploaded to Colab.
In Colab: click the folder icon on the left sidebar, then drag `assays.csv` into it.

If you're running this notebook locally (with Jupyter or Anaconda), put `assays.csv`
in the same folder as the notebook.

In [3]:
import pandas as pd

df = pd.read_csv(r"C:\Users\RexDe\Documents\Python\geodatascience-python-intro\video1\assays.csv")
df

     HoleID  From_m  To_m  Length_m  Au_gpt  Cu_pct           Lithology
0   DDH-001     0.0   2.0       2.0    0.02    0.01          Overburden
1   DDH-001     2.0   5.0       3.0    0.05    0.03  Weathered tonalite
2   DDH-001     5.0  12.5       7.5    0.18    0.05            Tonalite
3   DDH-001    12.5  18.0       5.5    1.24    0.08    Sheared tonalite
4   DDH-001    18.0  22.5       4.5    4.78    0.12    Quartz vein zone
5   DDH-001    22.5  28.0       5.5    6.32    0.15    Quartz vein zone
6   DDH-001    28.0  33.5       5.5    2.41    0.09    Sheared tonalite
7   DDH-001    33.5  40.0       6.5    0.31    0.04            Tonalite
8   DDH-001    40.0  50.0      10.0    0.08    0.02            Tonalite
9   DDH-002     0.0   3.0       3.0    0.01    0.01          Overburden
10  DDH-002     3.0  10.0       7.0    0.04    0.02             Diorite
11  DDH-002    10.0  18.5       8.5    0.15    0.34     Altered diorite
12  DDH-002    18.5  24.0       5.5    0.42    0.87   Chalcopyrite zone
13  DDH-002    24.0  31.0       7.0    0.58    1.12   Chalcopyrite zone
14  DDH-002    31.0  38.5       7.5    0.21    0.45     Altered diorite
15  DDH-002    38.5  45.0       6.5    0.06    0.03             Diorite
16  DDH-003     0.0   2.5       2.5    0.01    0.01          Overburden
17  DDH-003     2.5  12.0       9.5    0.03    0.02        Granodiorite
18  DDH-003    12.0  22.0      10.0    0.05    0.02        Granodiorite
19  DDH-003    22.0  35.0      13.0    0.04    0.03        Granodiorite
20  DDH-003    35.0  45.0      10.0    0.02    0.01        Granodiorite

In [5]:
# Summary statistics for all numeric columns
df.describe()

          From_m       To_m   Length_m     Au_gpt     Cu_pct
count  21.000000  21.000000  21.000000  21.000000  21.000000
mean   17.047619  23.714286   6.666667   0.810000   0.167619
std    13.690238  15.152204   2.851900   1.689473   0.299965
min     0.000000   2.000000   2.000000   0.010000   0.010000
25%     3.000000  12.000000   5.500000   0.040000   0.020000
50%    18.000000  22.500000   6.500000   0.080000   0.030000
75%    28.000000  35.000000   8.500000   0.420000   0.120000
max    40.000000  50.000000  13.000000   6.320000   1.120000

In [6]:
# Compute the mean gold grade across all intervals
df["Au_gpt"].mean()

np.float64(0.8100000000000003)

You just loaded a drillhole dataset and computed the mean gold grade. In four lines
of code. That's data science.

### 5.1 Filtering rows

Often you only want part of your data. Here we look at intervals from a single hole:

In [7]:
ddh001 = df[df["HoleID"] == "DDH-001"]
ddh001

    HoleID  From_m  To_m  Length_m  Au_gpt  Cu_pct           Lithology
0  DDH-001     0.0   2.0       2.0    0.02    0.01          Overburden
1  DDH-001     2.0   5.0       3.0    0.05    0.03  Weathered tonalite
2  DDH-001     5.0  12.5       7.5    0.18    0.05            Tonalite
3  DDH-001    12.5  18.0       5.5    1.24    0.08    Sheared tonalite
4  DDH-001    18.0  22.5       4.5    4.78    0.12    Quartz vein zone
5  DDH-001    22.5  28.0       5.5    6.32    0.15    Quartz vein zone
6  DDH-001    28.0  33.5       5.5    2.41    0.09    Sheared tonalite
7  DDH-001    33.5  40.0       6.5    0.31    0.04            Tonalite
8  DDH-001    40.0  50.0      10.0    0.08    0.02            Tonalite

Or just the high-grade intervals (anything above 1 g/t Au):

In [8]:
high_grade = df[df["Au_gpt"] > 1.0]
high_grade

    HoleID  From_m  To_m  Length_m  Au_gpt  Cu_pct         Lithology
3  DDH-001    12.5  18.0       5.5    1.24    0.08  Sheared tonalite
4  DDH-001    18.0  22.5       4.5    4.78    0.12  Quartz vein zone
5  DDH-001    22.5  28.0       5.5    6.32    0.15  Quartz vein zone
6  DDH-001    28.0  33.5       5.5    2.41    0.09  Sheared tonalite

### 5.2 Group statistics

`groupby` is one of the most powerful tools in pandas. It lets you compute
statistics per group — for example, mean grade by drillhole:

In [9]:
df.groupby("HoleID")["Au_gpt"].mean()

HoleID
DDH-001    1.71
DDH-002    0.21
DDH-003    0.03
Name: Au_gpt, dtype: float64

Or per lithology, which is genuinely useful for exploration geology:

In [10]:
df.groupby("Lithology")[["Au_gpt", "Cu_pct"]].mean().round(3)

                    Au_gpt  Cu_pct
Lithology
Altered diorite      0.180   0.395
Chalcopyrite zone    0.500   0.995
Diorite              0.050   0.025
Granodiorite         0.035   0.020
Overburden           0.013   0.010
Quartz vein zone     5.550   0.135
Sheared tonalite     1.825   0.085
Tonalite             0.190   0.037
Weathered tonalite   0.050   0.030

### 5.3 A simple plot

`matplotlib` is the standard plotting library. Here's a downhole plot of gold
grade for DDH-001 — exactly the kind of figure you'd put in a report.

In [1]:
import matplotlib.pyplot as plt

In [4]:
ddh001 = df[df["HoleID"] == "DDH-001"]

fig, ax = plt.subplots(figsize=(4, 7))
ax.barh(ddh001["From_m"], ddh001["Au_gpt"], height=ddh001["Length_m"],
        color="#A0522D", edgecolor="#2B2A26", align="edge")

ax.invert_yaxis()
ax.set_xlabel("Au (g/t)")
ax.set_ylabel("Depth (m)")
ax.set_title("DDH-001 — Gold grade by interval")
ax.grid(axis="x", linestyle=":", alpha=0.5)

plt.tight_layout()
plt.show()

:

That high-grade interval between 18 and 28 metres jumps out immediately — much
clearer than scanning a column of numbers.

We'll cover plotting properly in Video 3.

## What you did in this notebook

- Ran your first Python code
- Worked with variables and basic arithmetic
- Loaded a CSV file with `pandas`
- Computed summary statistics on a real drillhole dataset
- Filtered rows, grouped by category, and made a simple plot

That's already a useful chunk of practical data work.

### What's next

**Video 2** will go deeper into Python itself — variables, lists, dictionaries,
loops, functions — all with geoscience examples. **Video 3** will cover `pandas`
and `matplotlib` end-to-end on a real workflow.

Subscribe to the channel or follow along at
[botsontheground.com](https://botsontheground.com) for the next videos.

---

*Made for Frank Arnott Award participants and anyone else looking to bridge geology and data science.*
*— Drew Heasman, [botsontheground.com](https://botsontheground.com)*